In [9]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
np.random.randint(0, 10, (3, 3))


array([[6, 6, 7],
       [7, 9, 7],
       [9, 4, 7]])

In [80]:
arr6 = np.arange(10)
arr6
arr6[arr6.max()]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

9

In [83]:
arr7 = np.arange(9).reshape(3,3)
arr7
arr7[::-1,]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [3]:
np.random.randint(10, size=6)

array([9, 3, 5, 7, 7, 8])

In [4]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [16]:
arr=np.random.normal(0, 1, (3, 3))
arr
arr.ndim
arr.shape
arr.size
#bytes of each array
arr.itemsize

array([[-1.78772129,  0.21490686,  0.86553347],
       [ 1.04038626,  0.36748595,  1.0239744 ],
       [-0.66489041,  1.02832865, -1.3451981 ]])

2

(3, 3)

9

8

##### NumPy Basics - Array Indexing and Slicing

- We can use negative indices to index from the end of the array:
- 3rd row and last value from the 3rd column of x2: x2[2,-1]
- Slicing: - x[start:stop:step]



In [25]:
x1 = np.arange(10)
# Get the first 5 elements of x 
x1[0:5:]
# Elements after index 4
x1[4::]
# From 4th to 6th position
x1[4:7:]
# Return elements at even place (every other element)
x1[::2]
# reverse every other element starting from index 5
x1[5::-2]


array([0, 1, 2, 3, 4])

array([4, 5, 6, 7, 8, 9])

array([4, 5, 6])

array([0, 2, 4, 6, 8])

array([5, 3, 1])

- We can use this same approach with multi-dimensional slices. We can define multiple slices separated by commas:

In [30]:
x2 = np.array([[0,1,2], [3,4,5], [6,7,8]])
x2
x2.ndim
x2.shape
# Extract the first two rows and two columns
x2[:2,:2]
# all rows, every other column
x2[:,::2]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2

(3, 3)

array([[0, 1],
       [3, 4]])

array([[0, 2],
       [3, 5],
       [6, 8]])

In [34]:
# Reverse only the row positions
x2[::-1,:]
# Reverse the row and column positions
x2[::-1,::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

####   NumPy Basics - Reshaping and Concatenation

In [36]:
reshaped = np.arange(1, 10).reshape((3, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x3= np.random.random(10)#vecor array
x3
x3.reshape((1, 10))#2d array

array([0.42132124, 0.95688858, 0.71528413, 0.84827463, 0.86677792,
       0.98450494, 0.72345206, 0.60148444, 0.93669696, 0.49455406])

array([[0.42132124, 0.95688858, 0.71528413, 0.84827463, 0.86677792,
        0.98450494, 0.72345206, 0.60148444, 0.93669696, 0.49455406]])

- The concatenate() method allows us to put arrays together. 
- If required to combine arrays of different dimensions, **np.concatenate** might not be the best option to use . Instead, you can use np.vstack (vertical stack) or np.hstack(horizontal stack) to finish the task.
- Like concatenation, we can also perform horizontal and vertical splitting.

In [53]:
grid = np.arange(16).reshape((4, 4))
# Split vertically and print upper and lower arrays
upper, lower = np.vsplit(grid, [2])

x = np.arange(10)
#split at 3 and 6 index
x1, x2, x3 = np.split(x,[3,6])
print(x1, x2, x3)


[0 1 2] [3 4 5] [6 7 8 9]


#### Computations on NumPy Arrays

In [56]:
x = np.arange(10)

print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.power(x, 2))
print(np.mod(x, 2))

[ 5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  5 10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [57]:
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x / 5 =", x / 5)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x = [0 1 2 3 4 5 6 7 8 9]
x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5 = [ 0  5 10 15 20 25 30 35 40 45]
x / 5 = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2  =  [0 1 0 1 0 1 0 1 0 1]


#### Trignometry

In [55]:
theta = np.linspace(0, np.pi, 4)
theta

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [59]:
theta = np.linspace(0, np.pi, 4)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.04719755 2.0943951  3.14159265]
sin(theta) =  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
cos(theta) =  [ 1.   0.5 -0.5 -1. ]
tan(theta) =  [ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]


#### Logarthimic

In [60]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
ln(x)    = [0.         0.69314718 1.09861229]
log2(x)  = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


####  Universal Function Methods#
- **ufuncs** provide some methods that take two input parameters and return one output parameter. **reduce** and **accumulate** are two of the most important ones.
- Say we want to apply some operation to reduce an array to a single value. We can use the **reduce()**
- If we need to store all the intermediate results of the computation, we can use **accumulate()**

In [61]:
x = np.arange(1, 6)
sum_acc = np.add.accumulate(x)
sum_all = np.add.reduce(x)

print(x)
print(sum_acc)
print(sum_all)

[1 2 3 4 5]
[ 1  3  6 10 15]
15


#### Aggregations

In [67]:
x = np.random.random(10)
print("Sum of values is:", x.sum())
print("Mean value is: ", x.mean())
print("Max value is: ", x.max())
print("Min value is: ", x.min())


Sum of values is: 5.327843444409651
Mean value is:  0.5327843444409651
Max value is:  0.8312602520738568
Min value is:  0.0035187404226573182


In [72]:
# Row wise and column wise min
x = np.random.randint(1,10,(3,3))
x
print("Column wise minimum: ", np.amin(x, axis=0))
print("Row wise minimum: ", np.amin(x, axis=1))
x[::1,::2]

array([[9, 9, 9],
       [5, 9, 1],
       [5, 4, 7]])

Column wise minimum:  [5 4 1]
Row wise minimum:  [9 1 4]


array([[9, 9],
       [5, 1],
       [5, 7]])

#### Comparisons and Boolean Masks

In [76]:
x = np.arange(10)
print(x)

# How many values less than 6?
print(np.count_nonzero(x < 6))

# Are there any values greater than 8?
print(np.any(x > 8))

# Are all values less than 10?
print(np.all(x < 10))

(2 * x) == (x ** 2)

# Boolean array
print(x < 6)

# Boolean mask
print(x[x < 6])

[0 1 2 3 4 5 6 7 8 9]
6
True
True


array([ True, False,  True, False, False, False, False, False, False,
       False])

[ True  True  True  True  True  True False False False False]
[0 1 2 3 4 5]
